name: C++ Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build project with MSBuild
      run: msbuild SumDigits/SumDigits/SumDigits.vcxproj /p:Configuration=Debug /p:Platform="x64"

    - name: List output files
      run: dir SumDigits/SumDigits/x64/Debug

    - name: Run tests
      run: ./SumDigits/SumDigits/x64/Debug/SumDigits.exe
      timeout-minutes: 2
