name: C++ Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build project with MSBuild
      run: msbuild SumDigits/SumDigits.sln /p:Configuration=Release /p:Platform="x64"

    - name: Run tests
      run: ./SumDigits/x64/Release/test_sum_digits.exe
